In [101]:
import pandas as pd

In [102]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [103]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [105]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [106]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [107]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

In [108]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750051,25.351538
std,1125.977353,15.207589,23.685392,0.713590,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [109]:
df.isna().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [110]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'Purchase Amount (USD)' : 'purchase_amount'})

In [111]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [112]:
df = df.rename(columns={'purchase_amount_(usd)' : 'purchase_amount'})

In [113]:
print(df.columns.tolist())

['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'promo_code_used', 'previous_purchases', 'payment_method', 'frequency_of_purchases']

In [114]:
#create a column age_group
labels = ['Young Adult', 'Adult', 'Middle_aged','Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [115]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  Middle_aged
1   19  Young Adult
2   50  Middle_aged
3   21  Young Adult
4   45  Middle_aged
5   46  Middle_aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle_aged

In [116]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group'],
      dtype='object')

In [117]:
#create column purchase_frequency_days
frequency_mapping = {
'Fortnightly' : 14,
'Monthly' : 30,
'Quarterly' : 90,
'Biannually' : 180,
'Annually' : 365,
'Every 3 Months' : 90,
'Weekly' : 7
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [118]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [119]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [120]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle_aged,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle_aged,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adult,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle_aged,365.0

In [121]:
(df['discount_applied'] == df['promo_code_used']).all()

True

In [122]:
df = df.drop('promo_code_used', axis=1)

In [123]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [124]:
pip install pycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pycopg2-binary (from versions: none)
ERROR: No matching distribution found for pycopg2-binary

In [125]:
from sqlalchemy import create_engine
#step 1 : connect to postgresql
#replace placeholders with your actual details
username = "postgres"
password = "1234"
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}')

table_name = "customer"
df.to_sql(table_name, engine, if_exists='replace', index=False)
print(f"Data Succesfully loaded into table '{table_name}' in database '{database}'.")

Data Succesfully loaded into table 'customer' in database 'customer_behavior'.

In [126]:
import sys
print(sys.executable)
print(sys.version)

c:\ProgramData\anaconda3\python.exe
3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]

In [127]:
%pip install psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\hp\appdata\roaming\python\python312\site-packages (2.9.12)
Note: you may need to restart the kernel to use updated packages.

In [128]:
import pandas as pd
from sqlalchemy import create_engine

# CSV file load
df = pd.read_csv("customer_shopping_behavior.csv", encoding="latin1")

# PostgreSQL connection
username = "postgres"
password = "1234"
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# DataFrame ko PostgreSQL me load karna
table_name = "customer"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.

In [129]:
import os

print("Current Folder:", os.getcwd())
print("\nFiles in Folder:")
for file in os.listdir():
    print(file)

Current Folder: c:\Users\HP\Desktop\Customer Analysis

Files in Folder:
customer_shopping_behavior.csv
data_clean.ipynb

In [130]:
import os

print(os.path.exists("customer_shopping_behavior.csv"))

True

In [131]:
import os

print("Current Directory:")
print(os.getcwd())

print("\nFile Exists:")
print(os.path.exists("customer_shopping_behavior.csv"))

print("\nAbsolute Path:")
print(os.path.abspath("customer_shopping_behavior.csv"))

print("\nFile Size:")
print(os.path.getsize("customer_shopping_behavior.csv"))

Current Directory:
c:\Users\HP\Desktop\Customer Analysis

File Exists:
True

Absolute Path:
c:\Users\HP\Desktop\Customer Analysis\customer_shopping_behavior.csv

File Size:
416506

In [132]:
with open("customer_shopping_behavior.csv", "rb") as f:
    print(f.read(200))

b'\xef\xbb\xbfCustomer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,P'

In [133]:
with open("customer_shopping_behavior.csv", "rb") as f:
    data = f.read(200)

print(data)

b'\xef\xbb\xbfCustomer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,P'

In [134]:
with open("customer_shopping_behavior.csv", "r", errors="ignore") as f:
    for i in range(5):
        print(f.readline())

ï»¿Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases

1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly

2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly

3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly

4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly

In [135]:
import pandas as pd

print(pd.__version__)

2.2.2

In [136]:
import csv

with open(
    r"c:\Users\HP\Desktop\Customer Analysis\customer_shopping_behavior.csv",
    encoding="utf-8-sig"
) as f:
    reader = csv.reader(f)
    data = list(reader)

print("Rows:", len(data))
print("Columns:", len(data[0]))
print(data[:5])

Rows: 3901
Columns: 18
[['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Previous Purchases', 'Payment Method', 'Frequency of Purchases'], ['1', '55', 'Male', 'Blouse', 'Clothing', '53', 'Kentucky', 'L', 'Gray', 'Winter', '3.1', 'Yes', 'Express', 'Yes', 'Yes', '14', 'Venmo', 'Fortnightly'], ['2', '19', 'Male', 'Sweater', 'Clothing', '64', 'Maine', 'L', 'Maroon', 'Winter', '3.1', 'Yes', 'Express', 'Yes', 'Yes', '2', 'Cash', 'Fortnightly'], ['3', '50', 'Male', 'Jeans', 'Clothing', '73', 'Massachusetts', 'S', 'Maroon', 'Spring', '3.1', 'Yes', 'Free Shipping', 'Yes', 'Yes', '23', 'Credit Card', 'Weekly'], ['4', '21', 'Male', 'Sandals', 'Footwear', '90', 'Rhode Island', 'M', 'Maroon', 'Spring', '3.5', 'Yes', 'Next Day Air', 'Yes', 'Yes', '49', 'PayPal', 'Weekly']]

In [137]:
import csv
import pandas as pd

with open(
    r"c:\Users\HP\Desktop\Customer Analysis\customer_shopping_behavior.csv",
    encoding="utf-8-sig"
) as f:
    reader = csv.reader(f)
    data = list(reader)

df = pd.DataFrame(data[1:], columns=data[0])

print(df.head())

  Customer ID Age Gender Item Purchased  Category Purchase Amount (USD)  \
0           1  55   Male         Blouse  Clothing                    53
1           2  19   Male        Sweater  Clothing                    64
2           3  50   Male          Jeans  Clothing                    73
3           4  21   Male        Sandals  Footwear                    90
4           5  45   Male         Blouse  Clothing                    49

        Location Size      Color  Season Review Rating Subscription Status  \
0       Kentucky    L       Gray  Winter           3.1                 Yes
1          Maine    L     Maroon  Winter           3.1                 Yes
2  Massachusetts    S     Maroon  Spring           3.1                 Yes
3   Rhode Island    M     Maroon  Spring           3.5                 Yes
4         Oregon    M  Turquoise  Spring           2.7                 Yes

   Shipping Type Discount Applied Promo Code Used Previous Purchases  \
0        Express              Yes             Yes                 14
1        Express              Yes             Yes                  2
2  Free Shipping              Yes             Yes                 23
3   Next Day Air              Yes             Yes                 49
4  Free Shipping              Yes             Yes                 31

  Payment Method Frequency of Purchases
0          Venmo            Fortnightly
1           Cash            Fortnightly
2    Credit Card                 Weekly
3         PayPal                 Weekly
4         PayPal               Annually

In [138]:
import csv
import pandas as pd
from sqlalchemy import create_engine

# CSV file read
with open(
    r"c:\Users\HP\Desktop\Customer Analysis\customer_shopping_behavior.csv",
    encoding="utf-8-sig"
) as f:
    reader = csv.reader(f)
    data = list(reader)

# DataFrame create
df = pd.DataFrame(data[1:], columns=data[0])

print(df.head())

# PostgreSQL connection
engine = create_engine(
    "postgresql+psycopg2://postgres:1234@localhost:5432/customer_behavior"
)

# Load data into PostgreSQL
df.to_sql(
    "customer",
    engine,
    if_exists="replace",
    index=False
)

print("Data Successfully Loaded into PostgreSQL")

  Customer ID Age Gender Item Purchased  Category Purchase Amount (USD)  \
0           1  55   Male         Blouse  Clothing                    53
1           2  19   Male        Sweater  Clothing                    64
2           3  50   Male          Jeans  Clothing                    73
3           4  21   Male        Sandals  Footwear                    90
4           5  45   Male         Blouse  Clothing                    49

        Location Size      Color  Season Review Rating Subscription Status  \
0       Kentucky    L       Gray  Winter           3.1                 Yes
1          Maine    L     Maroon  Winter           3.1                 Yes
2  Massachusetts    S     Maroon  Spring           3.1                 Yes
3   Rhode Island    M     Maroon  Spring           3.5                 Yes
4         Oregon    M  Turquoise  Spring           2.7                 Yes

   Shipping Type Discount Applied Promo Code Used Previous Purchases  \
0        Express              Yes             Yes                 14
1        Express              Yes             Yes                  2
2  Free Shipping              Yes             Yes                 23
3   Next Day Air              Yes             Yes                 49
4  Free Shipping              Yes             Yes                 31

  Payment Method Frequency of Purchases
0          Venmo            Fortnightly
1           Cash            Fortnightly
2    Credit Card                 Weekly
3         PayPal                 Weekly
4         PayPal               Annually

Data Successfully Loaded into PostgreSQL

In [139]:
import pandas as pd
from sqlalchemy import create_engine

# Load CSV file
df = pd.read_csv(
    r"c:\Users\HP\Desktop\Customer Analysis\customer_shopping_behavior.csv",
    encoding="utf-8-sig"
)

# PostgreSQL connection details
username = "postgres"
password = "1234"
host = "localhost"
port = "5432"
database = "customer_behavior"

# Create connection
engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Load DataFrame into PostgreSQL table
table_name = "customer"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.

In [140]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [141]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [142]:
print(df.head())

   Customer ID  Age Gender Item Purchased  Category  Purchase Amount (USD)  \
0            1   55   Male         Blouse  Clothing                     53
1            2   19   Male        Sweater  Clothing                     64
2            3   50   Male          Jeans  Clothing                     73
3            4   21   Male        Sandals  Footwear                     90
4            5   45   Male         Blouse  Clothing                     49

        Location Size      Color  Season  Review Rating Subscription Status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   Shipping Type Discount Applied Promo Code Used  Previous Purchases  \
0        Express              Yes             Yes                  14
1        Express              Yes             Yes                   2
2  Free Shipping              Yes             Yes                  23
3   Next Day Air              Yes             Yes                  49
4  Free Shipping              Yes             Yes                  31

  Payment Method Frequency of Purchases
0          Venmo            Fortnightly
1           Cash            Fortnightly
2    Credit Card                 Weekly
3         PayPal                 Weekly
4         PayPal               Annually

In [144]:
df['age_group'] = pd.qcut(df['Age'], q=4, labels=labels)

In [145]:
df[['Age', 'age_group']].head()

   Age    age_group
0   55  Middle_aged
1   19  Young Adult
2   50  Middle_aged
3   21  Young Adult
4   45  Middle_aged

In [147]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases', 'age_group'],
      dtype='object')

In [148]:
df.to_sql('customer', engine, if_exists='replace', index=False)

900